Repository volatilityfoundation/volatility3, pull requests merged in 2025-01, with the labels that each got.

#1513 Add missing exception handling in env var recovery. Prevent backtraces
  volatility3/framework/plugins/linux/envars.py
Labels: parity-release

#1544 Linux: Ensure VMA enumration functions yield only valid objects consistently
  volatility3/framework/symbols/linux/extensions/__init__.py
Labels: parity-release

#1543 Linux and Windows: Ensure linked list object extensions consistently yield valid entries
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/windows/extensions/__init__.py
Labels: parity-release

#1542 linux: Ensure task listing functions yield only valid tasks
  volatility3/framework/plugins/linux/pslist.py
  volatility3/framework/symbols/linux/extensions/__init__.py
Labels: parity-release

#1550 Linux: Add support for Intel 32bit with PAE
  volatility3/framework/automagic/linux.py
Labels: parity-release

#1551 linux: pslist: fix task credentials rendering
  volatility3/framework/plugins/linux/pslist.py
Labels: parity-release

#1330 New linux plugin: modxview
  volatility3/framework/constants/_version.py
  volatility3/framework/constants/linux/__init__.py
  volatility3/framework/plugins/linux/check_modules.py
  volatility3/framework/plugins/linux/modxview.py
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/linux/utilities/__init__.py
  volatility3/framework/symbols/linux/utilities/tainting.py
Labels: parity-release

#1381 Volshell: Add Dedicated Method to retrieve EPROCESS/Task object
  volatility3/cli/volshell/linux.py
  volatility3/cli/volshell/windows.py
Labels: parity-release

#1568 #1473 - add exception handling on calls to registry get_key
  volatility3/framework/plugins/windows/envars.py
  volatility3/framework/plugins/windows/getservicesids.py
  volatility3/framework/plugins/windows/getsids.py
  volatility3/framework/plugins/windows/registry/userassist.py
  volatility3/framework/plugins/windows/svcscan.py
Labels: parity-release

#1490 Prevent infinite looping and out of memory errors #1482
  volatility3/framework/plugins/windows/handles.py
  volatility3/framework/symbols/windows/extensions/registry.py
Labels: parity-release

#1421 Issues/issue1418
  volatility3/framework/constants/_version.py
  volatility3/framework/contexts/__init__.py
  volatility3/framework/interfaces/context.py
Labels: parity-release

#1545 Linux - Harden mountinfo API and several related fixes
  volatility3/framework/objects/utility.py
  volatility3/framework/plugins/linux/mountinfo.py
  volatility3/framework/symbols/linux/__init__.py
  volatility3/framework/symbols/linux/extensions/__init__.py
Labels: awaiting-author-fixes, parity-release

#1557 Linux - Parity release - Harden pointer validation in several plugins and APIs
  volatility3/framework/plugins/linux/check_syscall.py
  volatility3/framework/plugins/linux/kmsg.py
  volatility3/framework/plugins/linux/proc.py
  volatility3/framework/plugins/linux/sockstat.py
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/linux/extensions/elf.py
Labels: parity-release

#1332 Linux: Address limitations in determining KASLR shifts by introducing VMCoreInfo support
  volatility3/framework/automagic/linux.py
  volatility3/framework/constants/linux/__init__.py
  volatility3/framework/plugins/linux/vmcoreinfo.py
  volatility3/framework/symbols/linux/__init__.py
Labels: awaiting-author-fixes

#1407 Windows: Update get_commit_charge extension to handle Core.CommitCharge case
  volatility3/framework/symbols/windows/extensions/__init__.py
Labels: parity-release
