Repository volatilityfoundation/volatility3, pull requests merged in 2025-03, with the labels that each got.

#1653 Fix crash-causing bugs. Add typing where possible.
  volatility3/framework/plugins/linux/kmsg.py
Labels: parity-release, linux_parity_push

#1654 Fix bugs in Linux memory region enumeration
  volatility3/framework/symbols/linux/extensions/__init__.py
Labels: parity-release, linux_parity_push

#1657 Report the memer name and type when attributes cannot be found
  volatility3/framework/interfaces/objects.py
Labels: parity-release

#1658 Correctly check tty instance to avoid backtrace
  volatility3/framework/plugins/linux/tty_check.py
Labels: parity-release, linux_parity_push

#1663 Fix several bugs in IDT verification for Linux
  volatility3/framework/plugins/linux/check_idt.py
Labels: parity-release, linux_parity_push

#1665 Prevent backtraces in netfilter due to smear
  volatility3/framework/plugins/linux/netfilter.py
Labels: parity-release, linux_parity_push

#1666 Properly decode values from ELF files even with partial smear
  volatility3/framework/symbols/linux/extensions/elf.py
Labels: parity-release, linux_parity_push

#1667 Ensure slot address is valid inside of array
  volatility3/framework/symbols/linux/__init__.py
Labels: parity-release, linux_parity_push

#1668 Gracefully terminate the plugin when the keyboard notifier list head …
  volatility3/framework/plugins/linux/keyboard_notifiers.py
Labels: parity-release, linux_parity_push

#1669 Prevent backtraces when the node head is smeared
  volatility3/framework/symbols/linux/__init__.py
Labels: parity-release, linux_parity_push

#1664 Correctly use decode with replace to avoid backtraces on partially sm…
  volatility3/framework/plugins/linux/envars.py
  volatility3/framework/plugins/linux/psaux.py
Labels: parity-release, linux_parity_push

#1670 Avoid smear in module enumeration paths
  volatility3/framework/plugins/linux/check_modules.py
  volatility3/framework/symbols/linux/utilities/tainting.py
Labels: parity-release, linux_parity_push

#1671 Fix several bugs found in the tracing plugins during mass testing
  volatility3/framework/plugins/linux/tracing/ftrace.py
  volatility3/framework/plugins/linux/tracing/tracepoints.py
Labels: parity-release, linux_parity_push

#1676 Fix how the task name is reported in getsids error path
  volatility3/framework/plugins/windows/getsids.py
Labels: parity-release

#1677 Add --tmpfs-only flag to RecoverFs to replace tmpfs plugin of Volatil…
  volatility3/framework/plugins/linux/pagecache.py
Labels: parity-release

#1661 Testing: enhance general design
  .github/workflows/test.yaml
  test/__init__.py
  test/plugins/linux/__init__.py
  test/plugins/linux/linux.py
  test/plugins/windows/windows.py
  test/test_volatility.py
Labels: parity-release

#1652 Add complete smear protection to linux.pstree
  volatility3/framework/plugins/linux/pstree.py
Labels: awaiting-author-response, parity-release, linux_parity_push

#1680 Fix timers and kpcrs bugs, missing smear checks, and API. Closes #1642
  volatility3/framework/plugins/windows/kpcrs.py
  volatility3/framework/plugins/windows/timers.py
Labels: parity-release

#1678 Fix unloaded modules bugs. Change API to fit current formats
  volatility3/framework/plugins/windows/unloadedmodules.py
Labels: awaiting-author-response, parity-release

#1684 Prevent truecrypt from throwing a backtrace when the module isn't fou…
  volatility3/framework/plugins/windows/truecrypt.py
Labels: parity-release

#1682 Bring hash dumping plugins up to current coding standards and error c…
  volatility3/framework/plugins/windows/cachedump.py
  volatility3/framework/plugins/windows/hashdump.py
  volatility3/framework/plugins/windows/lsadump.py
Labels: parity-release

#1675 Update the list_threads API to current standards and update current c…
  volatility3/framework/plugins/windows/debugregisters.py
  volatility3/framework/plugins/windows/suspended_threads.py
  volatility3/framework/plugins/windows/suspicious_threads.py
  volatility3/framework/plugins/windows/threads.py
Labels: parity-release

#1634 Symbols: Restore previous protection for non-native missing types
  volatility3/framework/symbols/intermed.py
Labels: parity-release

#1690 Convert poolscanning APIs to new coding standards
  volatility3/framework/plugins/windows/bigpools.py
  volatility3/framework/plugins/windows/callbacks.py
  volatility3/framework/plugins/windows/cmdscan.py
  volatility3/framework/plugins/windows/consoles.py
  volatility3/framework/plugins/windows/dlllist.py
  volatility3/framework/plugins/windows/driverscan.py
  volatility3/framework/plugins/windows/filescan.py
  volatility3/framework/plugins/windows/handles.py
  volatility3/framework/plugins/windows/indirect_system_calls.py
  volatility3/framework/plugins/windows/info.py
  volatility3/framework/plugins/windows/modscan.py
  volatility3/framework/plugins/windows/mutantscan.py
  volatility3/framework/plugins/windows/netscan.py
  volatility3/framework/plugins/windows/netstat.py
  volatility3/framework/plugins/windows/poolscanner.py
  volatility3/framework/plugins/windows/psscan.py
  volatility3/framework/plugins/windows/psxview.py
  volatility3/framework/plugins/windows/registry/hivescan.py
  volatility3/framework/plugins/windows/svcscan.py
  volatility3/framework/plugins/windows/symlinkscan.py
  volatility3/framework/plugins/windows/thrdscan.py
  volatility3/framework/plugins/windows/windowstations.py
Labels: parity-release

#1674 Change the type information reported for missing attributes
  volatility3/framework/interfaces/objects.py
Labels: awaiting-author-response, parity-release, linux_parity_push

#1691 Remove deepcopy call in pe_symbols. Validate wanted symbol informatio…
  volatility3/framework/plugins/windows/debugregisters.py
  volatility3/framework/plugins/windows/pe_symbols.py
  volatility3/framework/plugins/windows/skeleton_key_check.py
  volatility3/framework/plugins/windows/suspended_threads.py
  volatility3/framework/plugins/windows/unhooked_system_calls.py
Labels: parity-release

#1693 Fix handles API and callers. Bump version number and requirements
  volatility3/framework/plugins/windows/callbacks.py
  volatility3/framework/plugins/windows/dumpfiles.py
  volatility3/framework/plugins/windows/handles.py
  volatility3/framework/plugins/windows/poolscanner.py
  volatility3/framework/plugins/windows/psxview.py
Labels: parity-release

#1697 Ensure that new symbol tables are only created when needed. Avoid nam…
  volatility3/framework/plugins/windows/callbacks.py
  volatility3/framework/plugins/windows/driverscan.py
  volatility3/framework/plugins/windows/filescan.py
  volatility3/framework/plugins/windows/modscan.py
  volatility3/framework/plugins/windows/mutantscan.py
  volatility3/framework/plugins/windows/netscan.py
  volatility3/framework/plugins/windows/poolscanner.py
  volatility3/framework/plugins/windows/psscan.py
  volatility3/framework/plugins/windows/registry/hivescan.py
  volatility3/framework/plugins/windows/symlinkscan.py
  volatility3/framework/plugins/windows/thrdscan.py
  volatility3/framework/plugins/windows/windowstations.py
Labels: parity-release

#1673 Merge two Linux APIs for mapping kernel modules to pointers. Fix bugs…
  volatility3/framework/__init__.py
  volatility3/framework/deprecation.py
  volatility3/framework/plugins/linux/check_idt.py
  volatility3/framework/plugins/linux/check_modules.py
  volatility3/framework/plugins/linux/hidden_modules.py
  volatility3/framework/plugins/linux/keyboard_notifiers.py
  volatility3/framework/plugins/linux/kthreads.py
  volatility3/framework/plugins/linux/lsmod.py
  volatility3/framework/plugins/linux/modxview.py
  volatility3/framework/plugins/linux/netfilter.py
  volatility3/framework/plugins/linux/tracing/ftrace.py
  volatility3/framework/plugins/linux/tracing/tracepoints.py
  volatility3/framework/plugins/linux/tty_check.py
  volatility3/framework/symbols/linux/__init__.py
  volatility3/framework/symbols/linux/utilities/modules.py
Labels: awaiting-author-response, parity-release, linux_parity_push

#1696 Fix symbol table PDB API that mixes returns, None values, and exceptions
  volatility3/framework/plugins/windows/netstat.py
  volatility3/framework/symbols/windows/pdbutil.py
Labels: parity-release

#1656 Fix broken code and APIs in Linux networking paths
  volatility3/framework/plugins/linux/ip.py
  volatility3/framework/symbols/linux/extensions/network.py
Labels: awaiting-author-response, parity-release, linux_parity_push

#1686 Update fbdev plugin to gracefully handle old/broken symbol tables
  volatility3/framework/plugins/linux/graphics/fbdev.py
Labels: parity-release

#1704 No longer allocate session modules in support of the GUI objects at o…
  volatility3/framework/plugins/windows/windowstations.py
Labels: parity-release

#1711 Update symbol splitting to handle symbols without attached module name
  volatility3/framework/symbols/linux/utilities/modules.py
Labels: parity-release

#1708 Properly reconstruct strings from memory buffers and allow for plugin…
  volatility3/framework/constants/_version.py
  volatility3/framework/objects/utility.py
Labels: parity-release

#1710 Update nearly all callers of now deprecated Linux kernel APIs
  volatility3/framework/plugins/linux/check_idt.py
  volatility3/framework/plugins/linux/check_modules.py
  volatility3/framework/plugins/linux/hidden_modules.py
  volatility3/framework/plugins/linux/keyboard_notifiers.py
  volatility3/framework/plugins/linux/kthreads.py
  volatility3/framework/plugins/linux/lsmod.py
  volatility3/framework/plugins/linux/modxview.py
  volatility3/framework/plugins/linux/netfilter.py
  volatility3/framework/plugins/linux/tracing/ftrace.py
  volatility3/framework/plugins/linux/tracing/tracepoints.py
  volatility3/framework/plugins/linux/tty_check.py
  volatility3/framework/symbols/linux/utilities/modules.py
Labels: parity-release

#1715 Fix broken truncation from Vol3 bytes to string conversion
  volatility3/framework/objects/utility.py
Labels: parity-release

#1716 Add the windows plugin and associated extensions updates
  volatility3/framework/plugins/windows/windows.py
  volatility3/framework/plugins/windows/windowstations.py
  volatility3/framework/symbols/windows/extensions/gui.py
  volatility3/framework/symbols/windows/gui/gui-win10-10586-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-15063-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-16299-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-17134-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-17735-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-17763-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-18362-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-19041-x64.json
  volatility3/framework/symbols/windows/gui/gui-win10-19577-x64.json
  volatility3/framework/symbols/windows/gui/gui-win7sp0-x64.json
  volatility3/framework/symbols/windows/gui/gui-win7sp1-x64.json
  volatility3/framework/symbols/windows/gui/gui-win8-x64.json
Labels: parity-release

#1717 Update netfilter to current rookit detection API and update displayed…
  volatility3/framework/plugins/linux/netfilter.py
Labels: parity-release

#1718 Fix first set of ELF parsing unhandled smear protection
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/linux/extensions/elf.py
Labels: parity-release

#1720 Prevent backtrace on corrupt system call table entry
  volatility3/framework/plugins/linux/check_syscall.py
Labels: parity-release

#1721 Prevent backtrace on smeared iomem entry
  volatility3/framework/plugins/linux/iomem.py
Labels: parity-release

#1722 Fix bugs in kallsyms and the related pscallstack found in testing and…
  volatility3/framework/plugins/linux/kallsyms.py
  volatility3/framework/plugins/linux/pscallstack.py
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/linux/kallsyms.py
Labels: parity-release

#1723 Add needed checks to prevent backtraces in ELF parsing
  volatility3/framework/symbols/linux/extensions/__init__.py
Labels: parity-release

#1726 Add the recovery and reporting of LKM load parameters
  volatility3/framework/symbols/linux/utilities/modules.py
Labels: parity-release

#1727 Hopefully final round of kallsym fixes
  volatility3/framework/plugins/linux/kallsyms.py
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/linux/kallsyms.py
Labels: parity-release

#1728 Add performance event plugin to detect eBPF malware
  volatility3/framework/plugins/linux/tracing/perf_events.py
Labels: parity-release

#1733 Add a --script-only flag that exits after the given volshell script i…
  volatility3/cli/volshell/generic.py
Labels: parity-release

#1731 Add delete on close detection to process ghosting. Update plugin to c…
  volatility3/framework/plugins/windows/processghosting.py
Labels: parity-release

#1739 Fix checks in thrdscan that broke tests
  test/plugins/windows/windows.py
  volatility3/framework/plugins/windows/thrdscan.py
Labels: parity-release

#1740 Add module extraction API. Add plugin to directly extract modules. Ho…
  volatility3/framework/constants/linux/__init__.py
  volatility3/framework/plugins/linux/check_modules.py
  volatility3/framework/plugins/linux/hidden_modules.py
  volatility3/framework/plugins/linux/lsmod.py
  volatility3/framework/plugins/linux/module_extract.py
  volatility3/framework/symbols/linux/__init__.py
  volatility3/framework/symbols/linux/extensions/__init__.py
  volatility3/framework/symbols/linux/utilities/module_extract.py
  volatility3/framework/symbols/linux/utilities/modules.py
Labels: parity-release

#1746 Fix hidden_modules to actually list hidden modules...
  volatility3/framework/plugins/linux/hidden_modules.py
Labels: parity-release

#1736 Feature/use less memory
  volatility3/framework/interfaces/objects.py
Labels: parity-release
